version: '3.2'

services:
  easy-carte-api:
    build: ./easy-carte-api
    command: ./.docker/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./easy-carte-api:/easy-carte-api

  easy-carte-front:
    build: ./easy-carte-front
    command: ./.docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./easy-carte-front:/easy-carte-front